### PR TITLE
Add meta opertor status

### PR DESCRIPTION
**Pull request by horis233**
Implement Metaoperator controller status
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/35169

### CODE REVIEW

**Comment by gyliu513** [comment]
lgtm, only one minor comment, please do not commit `build/_output/bin/common-service-operator-local`, you can probably put `build` to `.gitignore`

**Comment by horis233** [comment]
@gyliu513 Thanks, I will add `build/_output/bin/common-service-operator-local` into the `.gitignore`

**Comment by gyliu513** [comment]
@horis233 adding folder `build` should be better?

**Comment by horis233** [comment]
@gyliu513 I ignore the temperate build file `build/_output` and `build/_test`, keep `bin` and `Dockerfile.`

**Comment by gyliu513** [comment]
@horis233 as we talked, please do not commit binaries into source code repo.

**Comment by horis233** [comment]
@gyliu513 Yes, `build/_output/bin/common-service-operator` and `build/_output/bin/common-service-operator-local` are removed from the repo and all the generated binaries will be ignored.

**Comment by gyliu513** [comment]
@horis233 the binaries are still in the code diff, need to be removed ;-)

**Comment by chenzhiwei** [comment]
Removed the binary from this repo, all the commits are affected.

The size is significantly reduced:

```
128M	old
748K	new
```

You need to clone this repo again and update patch, then submit new PR.

**Pull request closed without merging**
