### PR TITLE
add metaOperator status 

### PR DESCRIPTION
**Pull request by horis233**
This PR implements metaOperator status, ignores for binaries and adds code-dev functions in the Makefile.

### CODE REVIEW

**Comment by gyliu513** [comment]
Two minor comments:

1) We need to add some tests for this repo
2) For future PR like this, it is better to have two commits. One for manually changed code and another is for auto generated code.

/lgtm
/approve

**Comment by horis233** [comment]
@gyliu513 
Thanks! I will add some tests for this repo and separate manual changes and generated code in the future pull request.

**Comment by horis233** [comment]
@gyliu513 It seems this PR needs to be reviewed by the Github UI. Otherwise, the merging will be blocked.

**Pull request merged**
