### PR TITLE
Updated install to clarify ns name can be customized.

### PR DESCRIPTION
**Pull request by gyliu513**

### CODE REVIEW

**Comment by gyliu513** [comment]
@morvencao I think the lint is not right, can you help check?

```
./docs/install.md:17: MD007 Unordered list indentation
./docs/install.md:18: MD007 Unordered list indentation

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
common/Makefile.common.mk:63: recipe for target 'lint-markdown' failed
make: *** [lint-markdown] Error 123
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","time":"2020-01-29T13:01:48Z"}
```

**Comment by horis233** [comment]
@gyliu513 @morvencao 
The lint error is because the doctoc generates the TOC with indent 2, but our lint check requires indent 4.

**Pull request merged**
